### ISSUE TITLE
Error at market_basket step

### ISSUE THREAD

**Issue by ancient-learner** [loosolab/TF-COMB#77]
Hi I am getting the following error while running the market_basket function.
```

>>> C.TFBS_from_motifs(regions="./Peaks_hg19.bed", ````
motifs="./HOCOMOCOv11_HUMAN_motifs.txt",genome="./hg19.fa.gz",threads=12)
INFO: Scanning for TFBS with 12 thread(s)...
INFO: Progress: 10%
INFO: Progress: 20%
INFO: Progress: 30%
INFO: Progress: 40%
INFO: Progress: 51%
INFO: Progress: 60%
INFO: Progress: 70%
INFO: Progress: 81%
INFO: Progress: 95%
INFO: Finished!
INFO: Processing scanned TFBS
INFO: Identified 1181278 TFBS (401 unique names) within given regions
INFO: The attribute .TFBS now contains 1306796 TFBS (401 unique names)
>>> C.market_basket(threads=10)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ay328/.conda/envs/tfcomb_env/lib/python3.10/site-packages/tfcomb/objects.py", line 1129, in market_basket
    table = pd.melt(pair_counts_table, id_vars=["TF1"], var_name=["TF2"], value_name="TF1_TF2_count")  #long format (TF1, TF2, value)
  File "/home/ay328/.conda/envs/tfcomb_env/lib/python3.10/site-packages/pandas/core/reshape/melt.py", line 100, in melt
    raise ValueError(f"{var_name=} must be a scalar.")
ValueError: var_name=['TF2'] must be a scalar.

```
Pls let me know if I am doing something wrong

**Comment by hschult** [comment]
Hi!
thanks for reporting this error. Investigation showed that this is a bug connected to the installed `pandas` version. We are currently working on a fix. Until this is done please downgrade your pandas version to `2.0.0` as a workaround.

**Comment by ancient-learner** [comment]
> Hi! thanks for reporting this error. Investigation showed that this is a bug connected to the installed `pandas` version. We are currently working on a fix. Until this is done please downgrade your pandas version to `2.0.0` as a workaround.

THanls very much! It worked after downgrading pandas version :)

**Comment by thangnx1012** [comment]
Hi, 
I tried to install it as a conda environment in HPC, then run tf-comb v1.1.1, and got the same errors, even after downgrading pandas to 2.0.0 or 1.3.5. 
Perform market basket analysis
```
C.market_basket(threads=10)

Internal counts for 'TF_counts' were not set. Please run .count_within() to obtain TF-TF co-occurrence counts.
WARNING: No counts found in <CombObj>. Running <CombObj>.count_within() with standard parameters.
INFO: Setting up binding sites for counting
INFO: Counting co-occurrences within sites
INFO: Counting co-occurrence within background
INFO: Progress: 10%
INFO: Progress: 20%
INFO: Progress: 30%
INFO: Progress: 40%
INFO: Progress: 50%
INFO: Progress: 60%
INFO: Progress: 70%
INFO: Progress: 80%
INFO: Progress: 90%
INFO: Finished!
INFO: Done finding co-occurrences! Run .market_basket() to estimate significant pairs


ValueError                                Traceback (most recent call last)
Cell In[6], [line 2](vscode-notebook-cell:?execution_count=6&line=2)
      [1](vscode-notebook-cell:?execution_count=6&line=1) # Perform market basket analysis
----> [2](vscode-notebook-cell:?execution_count=6&line=2) C.market_basket(threads=10)
      [3](vscode-notebook-cell:?execution_count=6&line=3) # How many TFBS were found?
      [4](vscode-notebook-cell:?execution_count=6&line=4) C

File /cluster/projects/nn9632k/thangnx/software/miniconda3/envs/TF_COMB_env/lib/python3.10/site-packages/tfcomb/objects.py:1129, in CombObj.market_basket(self, measure, threads, keep_zero, n_baskets, _show_columns)
   [1127](https://vscode-remote+ssh-002dremote-002bsaga-002esigma2-002eno.vscode-resource.vscode-cdn.net/cluster/projects/nn9632k/thangnx/software/miniconda3/envs/TF_COMB_env/lib/python3.10/site-packages/tfcomb/objects.py:1127) pair_counts_table = pd.DataFrame(self.pair_counts, index=self.count_names, columns=self.count_names) #size n x n TFs
   [1128](https://vscode-remote+ssh-002dremote-002bsaga-002esigma2-002eno.vscode-resource.vscode-cdn.net/cluster/projects/nn9632k/thangnx/software/miniconda3/envs/TF_COMB_env/lib/python3.10/site-packages/tfcomb/objects.py:1128) pair_counts_table["TF1"] = pair_counts_table.index
-> [1129](https://vscode-remote+ssh-002dremote-002bsaga-002esigma2-002eno.vscode-resource.vscode-cdn.net/cluster/projects/nn9632k/thangnx/software/miniconda3/envs/TF_COMB_env/lib/python3.10/site-packages/tfcomb/objects.py:1129) table = pd.melt(pair_counts_table, id_vars=["TF1"], var_name=["TF2"], value_name="TF1_TF2_count")  #long format (TF1, TF2, value)
   [1131](https://vscode-remote+ssh-002dremote-002bsaga-002esigma2-002eno.vscode-resource.vscode-cdn.net/cluster/projects/nn9632k/thangnx/software/miniconda3/envs/TF_COMB_env/lib/python3.10/site-packages/tfcomb/objects.py:1131) #Add TF single counts to table
   [1132](https://vscode-remote+ssh-002dremote-002bsaga-002esigma2-002eno.vscode-resource.vscode-cdn.net/cluster/projects/nn9632k/thangnx/software/miniconda3/envs/TF_COMB_env/lib/python3.10/site-packages/tfcomb/objects.py:1132) vals = zip(self.count_names, self.TF_counts)

File /cluster/projects/nn9632k/thangnx/software/miniconda3/envs/TF_COMB_env/lib/python3.10/site-packages/pandas/core/reshape/melt.py:100, in melt(frame, id_vars, value_vars, var_name, value_name, col_level, ignore_index)
     [96](https://vscode-remote+ssh-002dremote-002bsaga-002esigma2-002eno.vscode-resource.vscode-cdn.net/cluster/projects/nn9632k/thangnx/software/miniconda3/envs/TF_COMB_env/lib/python3.10/site-packages/pandas/core/reshape/melt.py:96)         var_name = [
     [97](https://vscode-remote+ssh-002dremote-002bsaga-002esigma2-002eno.vscode-resource.vscode-cdn.net/cluster/projects/nn9632k/thangnx/software/miniconda3/envs/TF_COMB_env/lib/python3.10/site-packages/pandas/core/reshape/melt.py:97)             frame.columns.name if frame.columns.name is not None else "variable"
     [98](https://vscode-remote+ssh-002dremote-002bsaga-002esigma2-002eno.vscode-resource.vscode-cdn.net/cluster/projects/nn9632k/thangnx/software/miniconda3/envs/TF_COMB_env/lib/python3.10/site-packages/pandas/core/reshape/melt.py:98)         ]
     [99](https://vscode-remote+ssh-002dremote-002bsaga-002esigma2-002eno.vscode-resource.vscode-cdn.net/cluster/projects/nn9632k/thangnx/software/miniconda3/envs/TF_COMB_env/lib/python3.10/site-packages/pandas/core/reshape/melt.py:99) elif is_list_like(var_name):
--> [100](https://vscode-remote+ssh-002dremote-002bsaga-002esigma2-002eno.vscode-resource.vscode-cdn.net/cluster/projects/nn9632k/thangnx/software/miniconda3/envs/TF_COMB_env/lib/python3.10/site-packages/pandas/core/reshape/melt.py:100)     raise ValueError(f"{var_name=} must be a scalar.")
    [101](https://vscode-remote+ssh-002dremote-002bsaga-002esigma2-002eno.vscode-resource.vscode-cdn.net/cluster/projects/nn9632k/thangnx/software/miniconda3/envs/TF_COMB_env/lib/python3.10/site-packages/pandas/core/reshape/melt.py:101) else:
    [102](https://vscode-remote+ssh-002dremote-002bsaga-002esigma2-002eno.vscode-resource.vscode-cdn.net/cluster/projects/nn9632k/thangnx/software/miniconda3/envs/TF_COMB_env/lib/python3.10/site-packages/pandas/core/reshape/melt.py:102)     var_name = [var_name]

ValueError: var_name=['TF2'] must be a scalar.
```

When I run the jobs with pandas 2.0.0 or 1.3.5, it shows an error even from the start 
Setup a CombObj
```
from tfcomb import CombObj


C = CombObj()
```

**Comment by hschult** [comment]
Hi,
Thank you for reporting! The bug came back.
I did some testing on my side and pushed a fix to our dev branch. You can install it with `pip install git+https://github.com/loosolab/TF-COMB@dev`. Please let me know if that fixes it for you so I can create a new release.

Best regards

**Comment by thangnx1012** [comment]
Hi again,
I tried using Conda install v1.1, downgrading Pandas to 2.0.0 with Conda, and it worked; however, pip install v1.1.1 did not. I spent some time with the dev version, but it requires installing a lot of single packages, so it took a lot of time to actually run it, so I gave up 💃

**Comment by hschult** [comment]
What do you mean? The pip command should take care of installing all dependencies.

**Comment by thangnx1012** [comment]
Unfortunately, the command pip install git+https://github.com/loosolab/TF-COMB@dev did not include the dependency.
